(load "./modifiers.scm")
(load "./variant.scm")

(define (get-action)
  (string->symbol (read-line)))

(define (play variant)
  (define (action-loop state)
    (render-state variant state)
    (let* ((action (get-action))
           (outcome (perform-action variant state action))
           (message (get-message outcome))
           (new-state (get-state outcome)))
      (display message)
      (newline)
      (action-loop new-state)))
  (action-loop (initial-state variant)))

(define variant '())
(play variant)